version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"

  web:
    build: .
    container_name: django_web_app
    command: uvicorn volunteer_platform.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app # Mount current directory to /app in container for live changes
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
